services:
  beszel-agent:
    image: henrygd/beszel-agent:0.13.2
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - beszel_agent:/var/lib/beszel-agent
    env_file:
      - path: .env
volumes:
  beszel_agent:
