services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - dokploy-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`wraeclast.bishop-bass.ts.net`) && PathPrefix(`/grafana`)"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=tailscale"
      - "traefik.http.routers.grafana.tls.domains[0].main=wraeclast.bishop-bass.ts.net"
    environment:
      GF_SERVER_DOMAIN=wraeclast.bishop-bass.ts.net
      GF_SERVER_ROOT_URL=https://wraeclast.bishop-bass.ts.net/grafana
      GF_SERVER_SERVE_FROM_SUB_PATH=true
    env_file:
      - path: .env
volumes:
  grafana:
networks:
  dokploy-network:
    external: true
