services:
  silverbullet:
    image: ghcr.io/silverbulletmd/silverbullet
    restart: unless-stopped
    env_file:
      - path: .env
    volumes:
      - /home/sathyabhat/dockerdata/silverbullet/space:/space
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
